// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210919151917_InitialCreateSecondery")]
    partial class InitialCreateSecondery
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("API.Entities.Employees", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("userEmployee");
                });

            modelBuilder.Entity("API.Entities.TADAHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("instrumentsCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("lunchCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("paid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("travelCost")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("history");
                });
#pragma warning restore 612, 618
        }
    }
}
